In [4]:
import numpy as np
import math

In [3]:
np.asarray([1.0,1.0,1.0]).reshape(3,1)

array([[1.],
       [1.],
       [1.]])

In [5]:
theta = math.radians(45)

In [11]:
def R_ab(theta):
    return np.asarray([math.cos(theta),-math.sin(theta),0
                   ,math.sin(theta),math.cos(theta),0
                   ,0,0,1]).reshape(3,3)

In [12]:
R_ab(math.radians(180))

array([[-1.0000000e+00, -1.2246468e-16,  0.0000000e+00],
       [ 1.2246468e-16, -1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [9]:
theta

0.7853981633974483

In [13]:
theta = math.radians(180)

In [17]:
R_BC = np.asarray([1,0,0,
                  0,math.cos(theta),-math.sin(theta),
                  0,math.sin(theta),math.cos(theta)]).reshape(3,3)

In [19]:
R_BP = R_BC*np.identity(3)

In [20]:
R_BP

array([[ 1.,  0.,  0.],
       [ 0., -1., -0.],
       [ 0.,  0., -1.]])

In [22]:
P_BC = np.asarray([0,0,3]).reshape(3,1)

In [23]:
P_CP = np.asarray([2,1,2]).reshape(3,1)

In [24]:
P_BP = np.dot(R_BC,P_CP) + P_BC

In [27]:
P_BP.T

array([[ 2., -1.,  1.]])