In [5]:
import transforms3d as tfs
import numpy as np
import math

In [11]:
tfs.quaternions.quat2mat([math.sqrt(2)/2,0,0,math.sqrt(2)/2])

array([[ 0., -1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [4]:
tfs.quaternions.mat2quat(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]))

array([1., 0., 0., 0.])

In [13]:
tfs.quaternions.quat2axangle([math.sqrt(2)/2,0,0,math.sqrt(2)/2])

(array([0., 0., 1.]), 1.5707963267948966)

In [15]:
tfs.quaternions.axangle2quat([1,0,0],0.5)

array([0.96891242, 0.24740396, 0.        , 0.        ])

In [36]:
tfs.euler.euler2mat(math.pi/2,0,0,"sxyz")

array([[ 1.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  6.123234e-17, -1.000000e+00],
       [-0.000000e+00,  1.000000e+00,  6.123234e-17]])

In [25]:
tfs.euler.mat2euler(np.asarray( [[1,0,0],[0,0,1],[0,1,0],] ),"sxyz"  )

(1.5707963267948966, -0.0, 0.0)

In [46]:
tfs.euler.euler2axangle(0.36863547958726156, 0.34585912036052285, 0.06510734453095607,"sxyz")

(array([ 7.07106781e-01,  7.07106781e-01, -2.80468183e-17]),
 0.4999999999999995)

In [49]:
tfs.euler.axangle2euler([1,1,0],0.5,"sxyz")

(0.36863547958726156, 0.34585912036052285, 0.06510734453095607)