In [1]:
import numpy as np
import math
import transforms3d as tfs

In [3]:
R = np.asarray( [ [1.,0.,0.],[0.,1.,0.],[0.,0.,1.] ] )

In [6]:
T = np.asarray( [1,0,1] )

In [8]:
a = R,T

In [11]:
temp = np.hstack([R,T.reshape(3,1)])

In [15]:
np.vstack( (temp,[0,0,0,1]) )

array([[1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [16]:
np.vstack(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.]])

In [30]:
t = tfs.affines.compose(T,R,[1,1,1])

In [23]:
P_1 = np.asarray( [2,1,2] )

In [25]:
tfs.affines.compose(P_1,R,[1,1,1])

array([[1., 0., 0., 2.],
       [0., 1., 0., 1.],
       [0., 0., 1., 2.],
       [0., 0., 0., 1.]])

In [26]:
R_1 = tfs.euler.euler2mat(math.pi,0,0)

In [29]:
tfs.affines.compose(np.asarray( [0,0,3] ),R_1,[1,1,1])

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -1.0000000e+00, -1.2246468e-16,  0.0000000e+00],
       [ 0.0000000e+00,  1.2246468e-16, -1.0000000e+00,  3.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [35]:
tfs.quaternions.mat2quat( t[0:3,0:3] )

array([1., 0., 0., 0.])