In [1]:
import numpy as np
import transforms3d as tfs
import math

In [5]:
T_BC = tfs.affines.compose( [0,0,3],tfs.euler.euler2mat(math.pi,0,0),[1,1,1] )

In [11]:
T_BC

array([[ 1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0., -1.,  3.],
       [ 0.,  0.,  0.,  1.]])

In [10]:
T_BC = tfs.affines.compose( [0,0,3],tfs.quaternions.quat2mat([0,1,0,0]),[1,1,1] )

In [12]:
T_CP = tfs.affines.compose([2,1,2],np.identity(3),[1,1,1])

In [13]:
T_CP

array([[1., 0., 0., 2.],
       [0., 1., 0., 1.],
       [0., 0., 1., 2.],
       [0., 0., 0., 1.]])

In [14]:
T_BP = np.dot(T_BC,T_CP)

In [15]:
T_BP

array([[ 1.,  0.,  0.,  2.],
       [ 0., -1.,  0., -1.],
       [ 0.,  0., -1.,  1.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
tfs.euler.mat2euler(T_BP[:3,:3],"sxyz")

(3.141592653589793, -0.0, 0.0)

In [17]:
T_BE = tfs.affines.compose([0.5,0.6,0.8],tfs.quaternions.quat2mat([1,0,0,0]),[1,1,1])
T_CE = tfs.affines.compose([0.00,0.05,0.05],tfs.quaternions.quat2mat([0.707,0.706,0,0]),[1,1,1])
T_CO = tfs.affines.compose([0.00,0.02,0.85],tfs.quaternions.quat2mat([0.877,0.479,0,0]),[1,1,1])

In [20]:
T_BO = np.dot(T_BE,(np.dot(T_EC,T_CO)))

In [21]:
T_BO

array([[ 1.        ,  0.        ,  0.        ,  0.5       ],
       [ 0.        ,  0.8421333 ,  0.53926942,  1.39995674],
       [ 0.        , -0.53926942,  0.8421333 ,  0.83113231],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])